---
title: "Evaluating Forecast Accuracy"
output:
  html_document:
    toc: true
    df_print: paged
  github_document:
    toc: true
---

[Scott Burk's Video](https://www.youtube.com/watch?v=PvaKMQBR6nA&list=PLX-TyAzMwGs-I3i5uiCin37VFMSy4c50F&index=5)

# Forecast Error Statistics

## Forecast Error 

$$e_i=y_i-\hat{y_i}$$

$$\hat{y} = prediction$$

## Scale Dependent Measures of Error

<p class="text-center">Mean Absolute Error</p>

$$MAE = mean(|e_i|)$$

<p class="text-center">Root Mean Absolute Error</p>

$$RMSE=\sqrt(mean(e_i^2))$$

## Scale Independent Errors

Careful that $y$ is meaningful and not zero

<p class="text-center">Percentage Errors</p>

$$p_i = 100e_i/y_i$$
<p class="text-center">Mean Absolute Percentage Error</p>

$$MAPE=mean(|p_i|)$$

## Scale Independent, Scaled Error

<p class="text-center">Mean Absolute Scaled Error</p>

$$MASE=mean(|q_t|)$$
<p class="text-center">Where</p>

$$q_t = \frac{e_t}{\frac{1}{n-1}\sum_{i=2}^n|y_i-y_{i-1}|}$$

```{r}
library(fpp)
```
```{r}
beer2 <- window(ausbeer, 
                start = 1992,
                end = 2006-.1)
beerfit1 <- meanf(beer2, h=11)
beerfit2 <- naive(beer2, h=11)
beerfit3 <- snaive(beer2, h=11)

plot(beerfit1,
     main = "Forecasts for quartely beer production")
lines(beerfit2$mean, col = 2)
lines(beerfit3$mean, col = 3)
legend("topright", 
       lty = 1,
       col = c(4,2,3),
       legend = c("Mean Method", "Naive Method", "Seasonal Naive Method"))
```

```{r}
beer3 <- window(ausbeer, start = 2006)
accuracy(beerfit1, beer3)
```
```{r}
accuracy(beerfit2, beer3)
```
```{r}
accuracy(beerfit3, beer3)
```

```{r}
dj2 <- window(dj, end = 250)

plot(dj2,
     main = "Dow Jones Index (daily ending 15 Jul 94)",
     ylab = "",
     xlab = "Day",
     xlim = c(2, 290))
lines(meanf(dj2, h=42)$mean, col = 4)
lines(rwf(dj2, h=42)$mean, col = 2)
lines(rwf(dj2, drift=TRUE, h=42)$mean, col = 3)
legend("topleft",
       lty = 1,
       col = c(4,2,3),
       legend = c("Mean method", "Naive Method", "Drift Method"))
lines(dj)
```
```{r}
dj3 <- window(dj, start=251)
accuracy(meanf(dj2,h=42), dj3)
```
```{r}
accuracy(rwf(dj2,h=42), dj3)
```
```{r}
accuracy(rwf(dj2, drift = TRUE, h = 42), dj3)
```







