---
title: "Classical Decomposition: Additive and Multiplicative"
output:
  html_document:
    toc: true
    df_print: paged
  github_document:
    toc: true
---

[Scott Burk's Video](https://www.youtube.com/watch?v=vHoxz8ArxMQ&list=PLX-TyAzMwGs-I3i5uiCin37VFMSy4c50F&index=9)

```{r}
library(fpp2)
```

# Additive Decomposition

* Estimate Trend: $T_t$
* Calculate the De-trended Series: $y_t-T_t$
* Estimate Seasonal Components: $S_t$
* Remainder: $R_t=y_t-T_t-S_t$

```{r}
elecequip %>% 
  decompose(type = "additive") %>%
    autoplot() +
    xlab("Year") +
    ggtitle("Classical Additive Decomposition of Electrical Equipment Index")
```


# Multiplicative Decomposition

* Estimate Trend: $T_t$
* Calculate the De-trended Series: $\frac{y_t}{T_t}$
* Estimate Seasonal Components: $S_t$
* Remainder: $R_t=\frac{y_t}{T_t \times S_t}$


```{r}
elecequip %>% 
  decompose(type = "multiplicative") %>%
    autoplot() +
    xlab("Year") +
    ggtitle("Classical Multiplicative Decomposition of Electrical Equipment Index")
```


